sudo: require

install:
  - sudo apt-get install cowsay

script: 
  - export PATH=/usr/bin:/bin:/usr/games
  - cowsay "Test"
  - cowsay -f ./k3.cow "Hallo"
  - cowsay -f ./kathleen.cow "Hallo"
  - cowsay -f ./kathleen2.cow "Hallo"
  - cowsay -f ./klaasje.cow "Hallo"
